export const ALL_PET_REQUEST = "ALL_PET_REQUEST";
export const ALL_PET_SUCCESS = " ALL_PET_SUCCESS";
export const ALL_PET_FAIL = " ALL_PET_FAIL";

export const ADMIN_PET_REQUEST = "ADMIN_PET_REQUEST";
export const ADMIN_PET_SUCCESS = " ADMIN_PET_SUCCESS";
export const ADMIN_PET_FAIL = " ADMIN_PET_FAIL";


export const PET_DETAIL_REQUEST = "PET_DETAIL_REQUEST";
export const PET_DETAIL_SUCCESS = " PET_DETAIL_SUCCESS";
export const PET_DETAIL_FAIL = " PET_DETAIL_FAIL";

export const NEW_PET_REQUEST = "NEW_PET_REQUEST";
export const NEW_PET_SUCCESS = " NEW_PET_SUCCESS";
export const NEW_PET_RESET = " NEW_PET_RESET";
export const NEW_PET_FAIL = " NEW_PET_FAIL";

export const DELETE_PET_REQUEST = "DELETE_PET_REQUEST";
export const DELETE_PET_SUCCESS = " DELETE_PET_SUCCESS";
export const DELETE_PET_RESET = " DELETE_PET_RESET";
export const DELETE_PET_FAIL = " DELETE_PET_FAIL";

export const UPDATE_PET_REQUEST = "UPDATE_PET_REQUEST";
export const UPDATE_PET_SUCCESS = " UPDATE_PET_SUCCESS";
export const UPDATE_PET_RESET = " UPDATE_PET_RESET";
export const UPDATE_PET_FAIL = " UPDATE_PET_FAIL";

export const UPDATE_PET_STATUS_REQUEST = "UPDATE_PET_STATUS_REQUEST";
export const UPDATE_PET_STATUS_SUCCESS = " UPDATE_PET_STATUS_SUCCESS";
export const UPDATE_PET_STATUS_RESET = " UPDATE_PET_STATUS_RESET";
export const UPDATE_PET_STATUS_FAIL = " UPDATE_PET_STATUS_FAIL";

export const MY_PET_REQUEST = "MY_PET_REQUEST";
export const MY_PET_SUCCESS = "MY_PET_SUCCESS";
export const MY_PET_FAIL = "MY_PET_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";